spring.application.name=simple-jobs-spring-gradle
server.port=9002

job.system.delay=3000
job.manager.delay=15000
job.operator.delay=20000
job.risky.delay=60000

# OpenSearch
opensearch.name=simple-jobs-spring-gradle

# 운영 환경 구분 (local | dev | staging | prod)
opensearch.env=local

# OpenSearch 연결
opensearch.url=https://localhost:9200/_bulk
opensearch.username=admin
opensearch.password=Demo3543##

# 배치 설정
opensearch.trust-all-ssl=true
