spring.application.name=simple-jobs-spring-maven-with-java8
spring.main.web-application-type=none

job.system.delay=3000
job.manager.delay=15000
job.operator.delay=20000
job.risky.delay=60000

# OpenSearch
opensearch.name=simple-jobs-spring-maven-with-java8
opensearch.env=local
opensearch.url=https://localhost:9200/_bulk
opensearch.username=admin
opensearch.password=Demo3543##
opensearch.trust-all-ssl=true
