spring.application.name=simple-rest-spring-gradle
server.port=9202

# H2 In-Memory
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.sql.init.mode=always

# MyBatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.cube.simple.model

# OpenSearch
opensearch.name=simple-rest-spring-gradle
opensearch.env=local
opensearch.url=https://localhost:9200
opensearch.username=admin
opensearch.password=Demo3543##
opensearch.batch.max-size=200
opensearch.batch.max-message-size=32768
opensearch.connect-timeout-millis=3000
opensearch.read-timeout-millis=5000
opensearch.max-retries=3
opensearch.requeue-on-failure=true
opensearch.trust-all-ssl=true
opensearch.sleep-time=250
opensearch.max-queue-size=104857600
opensearch.persistent-writer-thread=false
opensearch.include-mdc=true
opensearch.include-kvp=true
opensearch.operation=index
opensearch.errors-to-stderr=true
