spring.application.name=simple-rest-spring-gradle
server.port=9202

# H2 In-Memory
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.sql.init.mode=always

# MyBatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.cube.simple.model

# OpenSearch
opensearch.name=simple-rest-spring-gradle
opensearch.env=local
opensearch.url=https://localhost:9200
opensearch.username=admin
opensearch.password=Demo3543##
opensearch.batch.max-bytes=1000000
opensearch.batch.flush-interval-seconds=1
opensearch.batch.queue-size=8192
